services:
  db_app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - OLLAMA_HOST=http://ollama:11434
    volumes:
      - .:/app
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    entrypoint: ["/bin/sh", "-c", "ollama serve & sleep 5 && ollama pull gemma3:1b && wait"]

    environment:
     - OLLAMA_KEEP_ALIVE=24h
     - OLLAMA_HOST=0.0.0.0

volumes:
  ollama_data: